import { AiOutlineFileText } from "react-icons/ai";
import {
  FaBook,
  FaChartBar,
  FaCrown,
  FaFileCode,
  FaGuitar,
  FaJava,
  FaPaintBrush,
} from "react-icons/fa";
import { FaComputer, FaMoneyBillTrendUp } from "react-icons/fa6";
import {
  GiMagnetBlast,
  GiReceiveMoney,
  GiShoonerSailboat,
} from "react-icons/gi";
import { MdOutlineViewKanban } from "react-icons/md";
import { PiPersonArmsSpread, PiShippingContainerBold } from "react-icons/pi";
import {
  SiBitbucket,
  SiCss3,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGodotengine,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiMysql,
  SiPixiv,
  SiPython,
  SiReact,
  SiRedux,
  SiSass,
  SiStorybook,
  SiStyledcomponents,
  SiTestinglibrary,
  SiThreedotjs,
  SiTypescript,
  SiVitest,
} from "react-icons/si";
import { TbDragDrop } from "react-icons/tb";

const shadowSize = "0 0 6px";

export const ALL_SKILLS = [
  "HTML",
  "CSS",
  "SCSS",
  "StyledComponents",
  "JS",
  "TS",
  "React",
  "Python",
  "Java",
  "Godot",
  "Redux",
  "Recharts",
  "RTL",
  "Vitest",
  "Jest",
  "Three",
  "Fabric",
  "Phaser",
  "PIXI",
  "Canvas",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Storybook",
  "CMS",
  "Kanban",
  "MySQL",
  "SoftSkills",
  "Economia",
  "Gestão",
  "Pascal",
  "Lazarus",
  "VB",
  "GeneralTI",
  "English",
  "Portuguese",
  "Spanish",
];

export const SKILLS = {
  HTML: {
    text: "HTML",
    bg: "#e34f26",
    color: "#ffffff",
    shadow: shadowSize + "#e34f26",
    icon: SiHtml5,
  },
  CSS: {
    text: "CSS",
    bg: "#264de4",
    color: "#ffffff",
    shadow: shadowSize + "#264de4",
    icon: SiCss3,
  },
  JS: {
    text: "JavaScript",
    bg: "#f7df1e",
    color: "#000000",
    shadow: shadowSize + "#f7df1e",
    icon: SiJavascript,
  },
  TS: {
    text: "TypeScript",
    bg: "#3178c6",
    color: "#ffffff",
    shadow: shadowSize + "#3178c6",
    icon: SiTypescript,
  },
  React: {
    text: "React",
    bg: "#61dafb",
    color: "#000000",
    shadow: shadowSize + "#61dafb",
    icon: SiReact,
  },
  Python: {
    text: "Python",
    bg: "#3776ab",
    color: "#ffffff",
    shadow: shadowSize + "#3776ab",
    icon: SiPython,
  },
  Java: {
    text: "Java",
    bg: "#007396",
    color: "#ffffff",
    shadow: shadowSize + "#007396",
    icon: FaJava,
  },
  Godot: {
    text: "Godot",
    bg: "#478cbf",
    color: "#ffffff",
    shadow: shadowSize + "#478cbf",
    icon: SiGodotengine,
  },
  SCSS: {
    text: "SCSS",
    bg: "#cd6799",
    color: "#ffffff",
    shadow: shadowSize + "#cd6799",
    icon: SiSass,
  },
  Redux: {
    text: "Redux",
    bg: "#764abc",
    color: "#ffffff",
    shadow: shadowSize + "#764abc",
    icon: SiRedux,
  },
  StyledComponents: {
    text: "Styled Components",
    bg: "#db7093",
    color: "#ffffff",
    shadow: shadowSize + "#db7093",
    icon: SiStyledcomponents,
  },
  Recharts: {
    text: "Recharts",
    bg: "#22c55e",
    color: "#ffffff",
    shadow: shadowSize + "#22c55e",
    icon: FaChartBar,
  },
  RTL: {
    text: "RTL",
    bg: "#e53935",
    color: "#ffffff",
    shadow: shadowSize + "#e53935",
    icon: SiTestinglibrary,
  },
  Vitest: {
    text: "Vitest",
    bg: "#6e9f18",
    color: "#ffffff",
    shadow: shadowSize + "#6e9f18",
    icon: SiVitest,
  },
  Jest: {
    text: "Jest",
    bg: "#99425b",
    color: "#ffffff",
    shadow: shadowSize + "#99425b",
    icon: SiJest,
  },
  Phaser: {
    text: "Phaser",
    bg: "#5c2d91",
    color: "#ffffff",
    shadow: shadowSize + "#5c2d91",
    icon: GiMagnetBlast,
  },
  PIXI: {
    text: "PIXI",
    bg: "#d42d85",
    color: "#ffffff",
    shadow: shadowSize + "#d42d85",
    icon: SiPixiv,
  },
  Three: {
    text: "Three.js",
    bg: "#000000",
    color: "#ffffff",
    shadow: shadowSize + "#000000",
    icon: SiThreedotjs,
  },
  Fabric: {
    text: "Fabric.js",
    bg: "#ff5722",
    color: "#ffffff",
    shadow: shadowSize + "#ff5722",
    icon: TbDragDrop,
  },
  Canvas: {
    text: "Canvas API",
    bg: "#000000",
    color: "#ffffff",
    shadow: shadowSize + "#ffffff",
    icon: FaPaintBrush,
  },
  Git: {
    text: "Git",
    bg: "#f05032",
    color: "#ffffff",
    shadow: shadowSize + "#f05032",
    icon: SiGit,
  },
  GitHub: {
    text: "GitHub",
    bg: "#181717",
    color: "#ffffff",
    shadow: shadowSize + "#ffffff",
    icon: SiGithub,
  },
  GitLab: {
    text: "GitLab",
    bg: "#fc6d26",
    color: "#ffffff",
    shadow: shadowSize + "#fc6d26",
    icon: SiGitlab,
  },
  Bitbucket: {
    text: "Bitbucket",
    bg: "#0052cc",
    color: "#ffffff",
    shadow: shadowSize + "#0052cc",
    icon: SiBitbucket,
  },
  Storybook: {
    text: "Storybook",
    bg: "#ff4785",
    color: "#ffffff",
    shadow: shadowSize + "#ff4785",
    icon: SiStorybook,
  },
  CMS: {
    text: "CMS",
    bg: "#4b6cb7",
    color: "#ffffff",
    shadow: shadowSize + "#4b6cb7",
    icon: PiShippingContainerBold,
  },
  Kanban: {
    text: "Kanban",
    bg: "#00aaff",
    color: "#ffffff",
    shadow: shadowSize + "#00aaff",
    icon: MdOutlineViewKanban,
  },
  MySQL: {
    text: "MySQL",
    bg: "#4479a1",
    color: "#ffffff",
    shadow: shadowSize + "#4479a1",
    icon: SiMysql,
  },
  Pascal: {
    text: "Pascal",
    bg: "#1e88e5",
    color: "#ffffff",
    shadow: shadowSize + "#1e88e5",
    icon: FaFileCode,
  },
  Lazarus: {
    text: "Lazarus",
    bg: "#0097a7",
    color: "#ffffff",
    shadow: shadowSize + "#0097a7",
    icon: FaBook,
  },
  VB: {
    text: "Visual Basic",
    bg: "#68217a",
    color: "#ffffff",
    shadow: shadowSize + "#68217a",
    icon: AiOutlineFileText,
  },
  SoftSkills: {
    text: "Soft Skills",
    bg: "#ff9800",
    color: "#ffffff",
    shadow: shadowSize + "#ff9800",
    icon: PiPersonArmsSpread,
  },
  Economia: {
    text: "Economia",
    bg: "#009688",
    color: "#ffffff",
    shadow: shadowSize + "#009688",
    icon: FaMoneyBillTrendUp,
  },
  Gestão: {
    text: "Gestão",
    bg: "#673ab7",
    color: "#ffffff",
    shadow: shadowSize + "#673ab7",
    icon: GiReceiveMoney,
  },
  GeneralTI: {
    text: "Ferramentas gerais TI",
    bg: "#607d8b",
    color: "#ffffff",
    shadow: shadowSize + "#607d8b",
    icon: FaComputer,
  },
  Portuguese: {
    text: "SkillsList.Portuguese",
    bg: "#006600",
    color: "#ffffff",
    shadow: shadowSize + "#006600",
    icon: GiShoonerSailboat,
  },
  English: {
    text: "SkillsList.English",
    bg: "#00247d",
    color: "#ffffff",
    shadow: shadowSize + "#00247d",
    icon: FaCrown,
  },
  Spanish: {
    text: "SkillsList.Spanish",
    bg: "#c60b1e",
    color: "#ffffff",
    shadow: shadowSize + "#c60b1e",
    icon: FaGuitar,
  },
};
